### ISSUE TITLE
Need information about Merchant Url for NFC - VAS flow

### ISSUE THREAD

**Issue by raghav18gupta** [kormax/apple-vas#3]
My client recently report that VAS flow is not working. We identified that the Merchant Url is configured but it does not exists (always returns 404).

The URL is pointing towards a server I maintain. Logs shows that server is getting the request from time to time. I suspect the flow is breaking because of missing Url. 

I need to develop the logic for this endpoint, but not sure what are the parameters, what's the return type, and so on.

**Comment by kormax** [comment]
I'm also interested in this information. I've also been able to cause a request to happen, but didn't manage to make it any further.

If you ever figure it out, I would be glad if you can report back on your findings.
